train_dataset:
  dataset:
    name: npy-file
    args:
      root_path: /data/jean.legoff/data/RESAC-SARGAS60/data/natl60_htuv_01102012_01102013.npz
      repeat: 20
      cache: bin
  wrapper:
    name: ssh-sr-implicit-downsampled
    args:
      inp_size: 48
      scale_min : 3
      scale_max: 9
      augment: true
      sample_q: 20736
  batch_size: 16

val_dataset:
  dataset:
    name: npy-file
    args:
      root_path: /data/jean.legoff/data/RESAC-SARGAS60/data/natl60_htuv_03_06_09_12-2008.npz
      repeat: 20
      cache: bin
  wrapper:
    name: ssh-sr-implicit-downsampled
    args:
      inp_size: 48
      scale_min : 3
      scale_max: 9
      sample_q: 20736
  batch_size: 16

data_norm:
  inp: {sub: [0], div: [1]}
  gt: {sub: [0], div: [1]}

model:
  name: liif
  args:
    encoder_spec:
      name: ssh-edsr-baseline
      args:
        no_upsampling: true
    imnet_spec:
      name: mlp
      args:
        out_dim: 1
        hidden_list: [256, 256, 256, 256]

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 200
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 5 #put higher than 1 like 10, saves time
epoch_save: 100